

x-common:
  &common
  restart: always
  env_file: ./scripts/cli/timezone.env
  networks:
    - backend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  postgresql:
    &postgresql
    << :
      - *common
      - *common-label
    image: ${LNMP_LIBRARY_NS:-library}/postgres:${LNMP_POSTGRESQL_VERSION:-14.0}-alpine
    environment:
      # - POSTGRES_PASSWORD_FILE=/run/secrets/db_root_password
      - POSTGRES_PASSWORD=${LNMP_POSTGRES_PASSWORD:-mytest}
      - POSTGRES_DB=${LNMP_POSTGRES_DB:-postgres}
      - POSTGRES_USER=${LNMP_POSTGRES_USER:-postgres}
    volumes:
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data
    ports:
      - "${LNMP_POSTGRESQL_PORT:-127.0.0.1:5432}:5432"
    secrets:
      # default is mysql password
      - db_root_password
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${LNMP_POSTGRES_DB:-postgres}", "-U", "${LNMP_POSTGRES_USER:-postgres}"]
      retries: 3
      timeout: 5s

secrets:
  db_root_password:
    << : *common-label
    file: ./secrets/${LNMP_DB_ROOT_PASSWORD_PATH:-db_root_password.txt}

volumes:
  postgresql-data:
    << : *common-label
