

x-common:
  &common
  restart: always
  env_file: ./scripts/cli/timezone.env
  networks:
    - backend
    - frontend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  nginx:
    volumes:
      - laravel_public:/app/laravel-docker/public
      - ./lrew/laravel/config/laravel.conf:/etc/nginx/conf.d/laravel.conf

  laravel:
    << :
      - *common
      - *common-label
    image: "khs1994/laravel:${LNMP_LARAVEL_TAG:-10}"
    volumes:
      # fpm config
      - ./config/php8/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      # php.ini
      - ./config/php8/php.ini:/usr/local/etc/php/php.ini:ro
      # php.ini override
      - ./config/php8/docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini:ro
      # log,etc
      - ./log/php:/var/log/php
      - ./lrew/laravel/.env.development:/app/laravel-docker/.env.development
      - laravel_views_cache:/app/laravel-docker/storage/framework/views
      - type: volume
        source: laravel_public
        target: /app/laravel-docker-public-volume
        volume:
          nocopy: true
      - laravel-vscode-server:/root/.vscode-server
      # - laravel-vscode-server-insiders:/root/.vscode-server-insiders
    expose:
      - "9000"
    command: php-fpm -R -F
    # entrypoint:
    #   - sh
    #   - -c
    #   - sleep 3600000
    environment:
      - APP_ENV=development
      - APP_DEBUG=${APP_DEBUG:-false}
      - LNMP_XDEBUG_REMOTE_HOST=${LNMP_XDEBUG_REMOTE_HOST:-192.168.199.100}
      - LNMP_XDEBUG_REMOTE_PORT=${LNMP_XDEBUG_REMOTE_PORT:-9003}
      - LNMP_OPCACHE_ENABLE=${LNMP_OPCACHE_ENABLE:-1}
    working_dir: /app
    cap_add:
      - CAP_SETGID
    depends_on:
      - laravel-chown

  laravel-chown:
    image: busybox
    command:
      - sh
      - -c
      - |
        chown 82:82 /app/laravel-docker/storage/framework/views
        chown -R 82:82 /app/laravel-docker-public-volume
    volumes:
        - laravel_views_cache:/app/laravel-docker/storage/framework/views
        - laravel_public:/app/laravel-docker-public-volume

volumes:
  laravel_public:
  laravel_views_cache:
  laravel-vscode-server:
  # laravel-vscode-server-insiders:
