name: istioctl
url: https://github.com/istio/istio/releases/download/${VERSION}/istioctl-${VERSION}-win.zip
url-mirror: https://download.fastgit.org/istio/istio/releases/download/${VERSION}/istioctl-${VERSION}-win.zip
version: 1.10.0
pre-version: 1.10.0
scripts:
  install:
    - _unzip $filename C:\bin\
  uninstall: _cleanup C:\bin\istioctl.exe
  version: istioctl version  --remote=false -s
  test: printInfo istioctl $(istioctl version  --remote=false -s) install success
command: istioctl
hash-url:
  sha256: https://github.com/istio/istio/releases/download/${VERSION}/istioctl-${VERSION}-win.zip.sha256
