kind: Pod
apiVersion: v1
metadata:
  name: host-ip
  labels:
    app: test
spec:
  containers:
    - name: test
      image: nginx:alpine
      ports:
        - containerPort: 80
          hostIP: 0.0.0.0
          hostPort: 80
          name: http
  hostNetwork: true
