

x-common:
  &common
  restart: always
  env_file: ./scripts/cli/timezone.env
  networks:
    - backend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  httpd:
    << :
      - *common
      - *common-label
    image: "${LNMP_LIBRARY_NS:-library}/httpd:${LNMP_HTTPD_VERSION:-2.4.53}-alpine"
    ports:
      - "${LNMP_HTTPD_HTTPS_PORT:-0.0.0.0:443}:443"
      - "${LNMP_HTTPD_HTTP_PORT:-0.0.0.0:80}:80"
    volumes:
      - ${APP_ROOT:-./app}:${LNMP_PHP_PATH:-/app}
      - ./config/etc/httpd/${LNMP_HTTPD_CONF:-httpd.conf}:/usr/local/apache2/conf/httpd.conf
      - ./config/${LNMP_HTTPD_CONF_D:-httpd}:/usr/local/apache2/conf.d
      - ./log/httpd:/usr/local/apache2/logs
    working_dir: /app
    networks:
      - frontend
    depends_on:
      - php8
