kind: Pod
apiVersion: v1
metadata:
  name: runtimeclasss-test
  labels:
    app: test
spec:
  # runtimeClassName: kata
  # runtimeClassName: kata-qemu
  # runtimeClassName: kata-fc

  runtimeClassName: runsc
  # runtimeClassName: runsc-kvm

  # runtimeClassName: crun
  # runtimeClassName: crun-disable-systemd

  # runtimeClassName: runc
  # runtimeClassName: runcv1
  # runtimeClassName: runclinux
  containers:
  - name: "test"
    image: nginx:alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: test
      mountPath: /opt/data
  # - name: "test2"
  #   image: khs1994/php:7.4.1-fpm-alpine
  volumes:
  - name: test
    emptyDir: {}
