

x-common:
  &common
  restart: always
  env_file: ./scripts/cli/timezone.env
  networks:
    - backend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  registry:
    << :
      - *common
      - *common-label
    image: ${LNMP_LIBRARY_NS:-library}/registry:${LNMP_REGISTRY_VERSION:-latest}
    networks:
      - frontend
      - backend
    # ports:
    #   - "5000:5000"
    volumes:
      - ./config/registry/${LNMP_REGISTRY_CONF:-config.yml}:/etc/docker/registry/config.yml:ro
      - type: volume
        source: registry-data
        target: /var/lib/registry

volumes:
  registry-data:
    << : *common-label
