

x-common:
  &common
  restart: always
  env_file: ./scripts/cli/timezone.env
  networks:
    - backend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  mongodb:
    << :
      - *common
      - *common-label
    image: ${LNMP_LIBRARY_NS:-library}/mongo:${LNMP_MONGODB_VERSION:-5.0.3}
    volumes:
      - ./config/mongodb/${LNMP_MONGODB_CONF:-mongod.conf}:/etc/mongod.conf:ro
      - type: volume
        source: mongodb-data
        target: /data/db
      - ./log/mongodb/mongo.log:/var/log/mongodb/mongo.log
    ports:
      - "${LNMP_MONGODB_PORT:-127.0.0.1:27017}:27017"
    command: ["mongod","--config","/etc/mongod.conf"]

volumes:
  mongodb-data:
    << : *common-label
