name: Check Link

on:
  workflow_dispatch:

jobs:
  check-link:
    name: check-link
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      # search Issues :-(
      - uses: azure/docker-login@v1
        if: |
          github.event_name == 'push'
        with:
          # login-server: contoso.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker run -i --rm \
          -v $PWD:/mnt:ro \
          dkhamsing/awesome_bot \
          --white-list "localhost","0.0.0.0",\
          "server","example.com","docker",\
          "docker.domain.com","YourIP","register",\
          "https://www.freedesktop.org/wiki/Software/systemd/",\
          "cloud.tencent.com",\
          "storage.khs1994.com",\
          "test2.t.khs1994.com",\
          "harbor.t.khs1994.com",\
          "packages.t.khs1994.com",\
          "registry.t.khs1994.com",\
          "minio.t.khs1994.com",\
          "t.khs1994.com",\
          "192.168.199.100",\
          "192.168.57.1",\
          "192.168.57.112",\
          "192.168.64.98",\
          "127.0.0.1",\
          "IP",\
          "kubernetes.default.svc.cluster.local",\
          "github.com/settings/tokens",\
          "mritd.me",\
          "my.oschina.net",\
          "xxx",\
          "www.aliyun.com" \
          --allow-dupe \
          --skip-save-results \
          -t 10 \
          `find . \( -path "./a" -o -path "./b" \) -prune -o -name "*.md" -exec ls {} \;`
        name: check-link
        # timeout-minutes: 25
