name: Docker Image rootfs

on:
  workflow_dispatch:

env:
  LNMP_CN_ENV: 'false'

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 2
      - name: Download docker hub docker image rootfs
        shell: pwsh
        run: |
          . ./windows/sdk/dockerhub/rootfs.ps1
          rootfs hello-world
        # env:
        #   DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        #   DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - name: Download aliyun docker image rootfs
        shell: pwsh
        run: |
          . ./windows/sdk/dockerhub/rootfs.ps1
          rootfs khs1994/hello-world latest '' '' '' 0 registry.us-west-1.aliyuncs.com
        # env:
        #   DOCKER_USERNAME: ${{secrets.DOCKER_ALIYUN_USERNAME}}
        #   DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - name: Download tencent cloud docker image rootfs
        shell: pwsh
        run: |
          . ./windows/sdk/dockerhub/rootfs.ps1
          rootfs khs1994/hello-world latest '' '' '' 0 uswccr.ccs.tencentyun.com
        # env:
        #   DOCKER_USERNAME: ${{secrets.DOCKER_TENCENT_CLOUD_USERNAME}}
        #   DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - name: Download mirror.gcr.io docker image rootfs
        shell: pwsh
        run: |
          . ./windows/sdk/dockerhub/rootfs.ps1
          rootfs hello-world latest '' '' '' 0 mirror.gcr.io
        # env:
        #   DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        #   DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        continue-on-error: true
      - name: List docker image rootfs
        run: |
          ls ~/.khs1994-docker-lnmp/dockerhub
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 2
      - name: Download docker hub docker image rootfs
        run: |
          bash ./windows/sdk/dockerhub/rootfs.sh hello-world
        # env:
        #   DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        #   DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - name: Download aliyun docker image rootfs
        run: |
          bash ./windows/sdk/dockerhub/rootfs.sh \
          khs1994/hello-world latest '' '' '' 0 registry.us-west-1.aliyuncs.com
        # env:
        #   DOCKER_USERNAME: ${{secrets.DOCKER_ALIYUN_USERNAME}}
        #   DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - name: Download tencent cloud docker image rootfs
        run: |
          bash ./windows/sdk/dockerhub/rootfs.sh \
          khs1994/hello-world latest '' '' '' 0 uswccr.ccs.tencentyun.com
        # env:
        #   DOCKER_USERNAME: ${{secrets.DOCKER_TENCENT_CLOUD_USERNAME}}
        #   DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - name: Download mirror.gcr.io docker image rootfs
        run: |
          bash ./windows/sdk/dockerhub/rootfs.sh \
          hello-world latest '' '' '' 0 mirror.gcr.io
        # env:
        #   DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        #   DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        continue-on-error: true
      - name: List docker image rootfs
        run: |
          ls -la ~/.khs1994-docker-lnmp/dockerhub
      - name: lpm-on-linux
        run: |
          ./lpm.ps1 install coredns
